name: Cranix Ltd Build Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --name "Cranix Server Installer Win" mc_installer.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4 # CHANGED TO V4
        with:
          name: Cranix-Windows-Installer
          path: dist/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests pyinstaller

      - name: Build Mac Executable
        run: |
          pyinstaller --onefile --name "Cranix_Server_Installer_Mac" mc_installer.py

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4 # CHANGED TO V4
        with:
          name: Cranix-Mac-Installer
          path: dist/Cranix_Server_Installer_Mac